image:
  names:
    app: botalovegor46/otus:1.0.12
    liquibase: botalovegor46/liquibase-otus:1.0.1
    postgres: postgres:12

replicas:
  app: 3
  postgres: 1

configmaps:
  db: db-config
  app: app-config
secrets:
  db: db-secrets

db:
  driver_class_name: org.postgresql.Driver
  name: postgres
  user: postgres
  password: 1

ports:
  app:
    name: app-port
    number: 8000
  postgres:
    name: db-port
    number: 5432

app:
  name: otus

ingress:
  host: arch.homework

metrics:
  app:
    interval: 15s
    path: /actuator/prometheus
