apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: otus
  name: otus-deployment
  labels:
    app: deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: otus-app
  template:
    metadata:
      labels:
        app: otus-app
    spec:
      containers:
        - name: otus-app
          image: botalovegor46/otus:1.0.2
          ports:
            - name: otus-port
              containerPort: 8000
          envFrom:
            - configMapRef:
                name: otus-db-config
      initContainers:
        - name: liquibase-otus
          image: botalovegor46/liquibase-otus:1.0.1
          envFrom:
            - configMapRef:
                name: otus-db-config