---
apiVersion: v1
kind: Service
metadata:
  namespace: otus
  name: postgres-service
spec:
  type: NodePort
  ports:
   - port: 5432
     targetPort: 5432
  selector:
    app: postgres

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: otus
  name: postgres-statefulset
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:12
        ports:
        - containerPort: 5432
          name: postgredb
        envFrom:
          - configMapRef:
              name: postgres-db-config
          - secretRef:
              name: otus-db-secrets
        volumeMounts:
        - name: postgredb
          mountPath: /var/lib/postgresql/data
          subPath: postgres
  volumeClaimTemplates:
  - metadata:
      name: postgredb
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 4Gi