apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-postgres-service
spec:
  type: NodePort
  ports:
    - port: {{.Values.ports.postgres.number}}
      name: {{.Values.ports.postgres.name}}
      targetPort: {{.Values.ports.postgres.number}}
  selector:
    app: {{ .Release.Name }}-postgres